feature/nodemailer-front
citi-onboarding/PubliEasy pull request #12
Opened 2023-06-12 07:19 UTC by renatomsa

## What I did

- Added Nodemailer front-end component
- Added Material UI lib
- Added Unform

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. `git checkout develop`
   1. `git pull`
   1. `git checkout feature/nodemailer-component-front`
   1. `git pull`
   1. `yarn`
   1. `code .`
   1. `yarn start`

1. In your browser go to http://localhost:3000

1. Check if the component looks just like the mockup in deferent screen sizes 

1. Read the changed files section on GitHub 

1. Test the things that you think are worth testing, even the ones that are not in this description 

&nbsp;
***
**Time spent:** 4h30min

2023-06-15 16:23 UTC, jamillalobo requested changes
Ficou muito massa o nodemailer, Nanato! Eu testei, creio que tu deve ter recebido alguma mensagem, acho que como sugestão eu só veria se tem a possibilidade de fazer alguns ajustes no front:

- Quando eu escrevia algo no input, a legenda de dentro do input acabava subindo e ficava no meio fio do input. Outra situação foi quando não era respondido nada, aí a legenda não voltava pro lugar normal dentro do input, como estava antes. 

Eu acho que é uma questão mais de detalhes mesmo, não sei se seria necessário uam correção tão grande, mas no geral só de estar funcionando, já está muito massa, parabéns mesmo!

2023-08-01 03:20 UTC, damattag requested changes

2023-08-01 03:20 UTC, damattag commented on server/.env
> +EMAIL_WILL_RECEIVE=contatopublieasy@gmail.com
aqui precisa colocar o email do cara pra enviar e receber o email, não é o citi necessariamente que manda

2023-08-01 03:22 UTC, damattag requested changes

2023-08-01 03:22 UTC, damattag commented on server/.env
>  PASSWORD="ckwl qdqe depd tvar"
cê vai precisar da senha deles, eles vão gerar uma senha e te entregar

2023-08-01 03:24 UTC, damattag commented on server/.env
>  PASSWORD="ckwl qdqe depd tvar"
é uma senha especial que nas configurações do google fica como "senhas de app", que fica dentro de autenticação de dois fatores, depois te mostro se precisar e você passa pro cliente

2023-08-08 23:15 UTC, damattag approved these changes

2023-08-23 16:06 UTC, merged