Feature/services
citi-onboarding/PubliEasy pull request #2
Opened 2023-05-30 15:21 UTC by jamillalobo

## What I did

- Thing I’ve done 
- Thing I’ve done
   - Detailing
   - Detailing

## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. `git checkout develop`
   1. `git pull`
   1. `git checkout <branch name>`
   1. `git pull origin <branch name>`
   1. `yarn install`
   1. `code .`
   1. `yarn start`

1. In your browser go to http://localhost:3000

1. Check if the component looks just like the mockup in deferent screen sizes 

1. Read the changed files section on GitHub 

1. Test the things that you think are worth testing, even the ones that are not in this description 

&nbsp;
***
**Time spent:** 4h30min

**Resolves:** #<issue number>

2023-06-01 17:42 UTC, rafaelaleao5 submitted a review, later dismissed
tudo certo, so falta a fonte mesmo

2023-06-05 23:33 UTC, renatomsa requested changes
Ficou massa!!

Só pensei no seguinte:
Minha tela é menor, daí as imagens ficaram bem juntinhas, fora a margem q ficou um pouco p fora.

Pode ser feito isso:
- Colocar a ```width``` em porcentagem (ex: 75%) e altura setar em px (ex: 150px) na tag ```<ItemTag>```

- Colocar a ```width``` do ```ServicesContainer``` menor (ex: 80%) p ficar mais parecido com o figma
- setar ```margin: 0 auto;``` no ```ServicesContainer```, assim ficará no meio da tela;

- Retirar o ```margin-left``` da tag ```<Title>```

- Trocar ```margin``` por ```margin-top``` em ```<Products>``` pq com o margin auto do container, ficará no meio

Ótimo trabalho, Jam!!

2023-06-08 20:23 UTC, renatomsa submitted a review, later dismissed

2023-06-08 23:15 UTC, renatomsa approved these changes
Pode dar o merge!!

2023-06-08 23:22 UTC, merged