Feature/about us
citi-onboarding/PubliEasy pull request #3
Opened 2023-05-31 18:35 UTC by rafaelaleao5

## What I did

- NavBar
   - Logo na esquerda
   - Lista com os 4 links (sendo cada um um item da lista) e o contato destacado com uma borda com linear gradient (dentro de uma div)
   - Navbar fixa independente da rolagem da pagina
- About Us
   - Div com o espaço geral do sobre nos
   - Div com a parte da foto como background e dentro dela a div dos textos e o botão de rolagem (botao no centro e embaixo)
   - Na div dos textos, outra tag para a ultima palavra diferenciar a cor, texto alinhado na direita 
   - Paragrafo com o Lorem ipsum, com a ultima frase com outra tag para diferenciar a espessura 

OBS.: eu me confundi e fiz a maioria das coisas tanto da nav bar quanto do aboutus nessa branch, ai só vou enviar essa mesmo
## How to test

1. Open the terminal and go to the folder of this project

1. In terminal:
   1. `git checkout develop`
   1. `git pull`
   1. `git checkout feature/aboutUs`
   1. `git pull origin feature/aboutUs`
   1. `yarn install`
   1. `code .`
   1. `yarn start`

1. In your browser go to http://localhost:3000

1. Check if the component looks just like the mockup in deferent screen sizes 

1. Read the changed files section on GitHub 

1. Test the things that you think are worth testing, even the ones that are not in this description 

&nbsp;
***
**Time spent:** 4h30min

**Resolves:** #<issue number>

2023-06-05 23:40 UTC, renatomsa requested changes
Massa, Rafa!!

Só alguns comentários pq na minha tela ficou um pouco juntinho as coisas da NavBar:

- Adicionar ```justify-content: space-between```; e ```width: 50%```, (valor como exemplo) para a navbar ficar no meio automaticamente e responsivamente;

- Retirar o ```margin: 35px```; da tag ```<li>```;

- Retirar o ```margin-left: 35px```; da tag ```.module-wrap```;

- Retirar o ```padding``` da tag ```<a>```;

- Após setar a tag ```<ul>``` com justify-content aproveitando o recurso da flexbox, não precisa ficar adicionando margens nas outras tags, assim a navbar ficará mais fluida!

Ótimo trabalho, Rafa! Parabéns!!

2023-06-06 15:16 UTC, jamillalobo submitted a review, later dismissed
Achei massa a construção do código, Rafa, apareceu certinho pra mim no yarn start! Como sugestão, eu colocaria tags com nomes mais específicos no index.tsx da navbar, pra facilitar o entendimento do que é cada div.

2023-06-06 17:36 UTC, renatomsa submitted a review, later dismissed

2023-06-08 20:15 UTC, renatomsa requested changes
Massa, Rafa!!

Só um último detalhe:

- Em alguns tamanhos de tela, a imagem do botão com a seta p/ baixo está se movimentando, isso acontece pq está numa div e a propriedade ```padding-top``` está setada com uma medida relativa, portanto para consertar basta utilizar uma medida absoluta, como px, então caso mude o estilo da tag ```<ImageButtom>``` para ```padding-top: 400px;```, por exemplo, ficará correto!

Parabéns pela dedicação!!

2023-06-08 23:53 UTC, renatomsa approved these changes

2023-06-08 23:55 UTC, renatomsa requested changes
Resolve conflicts w/ develop

2023-06-09 01:08 UTC, renatomsa approved these changes
Pode dar merge!!

2023-06-09 01:20 UTC, merged